package org.example.badsmells;

/*
 * Smell: Divergent Change
 *
 * This class handles report formatting, SQL generation, and CSV export. Those
 * are different reasons to change, so they should not be forced into one class.
 *
 * Proposed Refactorings:
 * - Extract separate classes for reporting, SQL persistence, and CSV export.
 * - Move fields and methods to the modules that change for the same reason.
 */
public class DivergentChangeExample {

	public static class StudentReportFormatter {
		private String reportTitle = "Exam Results";
		private String reportFooter = "Generated by registrar office";

		public String format(String name, int score) {
			return reportTitle + "\n" + name + ": " + score + "\n" + reportFooter;
		}
	}

	public static class StudentSqlBuilder {
		private String tableName = "exam_results";
		private String databaseUrl = "jdbc:mysql://localhost:3306/school";

		public String buildInsert(String name, int score) {
			return "/* " + databaseUrl + " */ INSERT INTO " + tableName +
					"(name, score) VALUES ('" + name + "', " + score + ")";
		}
	}

	public static class StudentCsvExporter {
		private String csvSeparator = ",";
		private boolean includeHeader = true;

		public String export(String name, int score) {
			String csv = name + csvSeparator + score;
			if (includeHeader) {
				return "name" + csvSeparator + "score\n" + csv;
			}
			return csv;
		}
	}

	public void clientCode() {
		StudentReportFormatter reportFormatter = new StudentReportFormatter();
		StudentSqlBuilder sqlBuilder = new StudentSqlBuilder();
		StudentCsvExporter csvExporter = new StudentCsvExporter();

		System.out.println(reportFormatter.format("Nino", 95));
		System.out.println(sqlBuilder.buildInsert("Nino", 95));
		System.out.println(csvExporter.export("Nino", 95));
	}

}
